# SentinelEdge Configuration
# Focus on functionality, keep it simple

[threat_detection]
provider = "rule_engine"  # Use rule-based detection, no external API dependency
enable_heuristics = true
confidence_threshold = 0.7

[response]
log_file = "./sentinel-edge.log"
enable_quarantine = false
enable_process_kill = false
alert_threshold = 0.7

[monitoring]
monitor_network = true
monitor_processes = true
monitor_files = true

# Sensitive paths to monitor
sensitive_paths = [
    "/etc/passwd",
    "/etc/shadow",
    "/root/.ssh",
    "/home/*/.ssh"
]

# System processes to ignore
trusted_processes = [
    "systemd",
    "kthreadd"
] 