version: '3.8'

services:
  sentinel-edge:
    build: .
    container_name: sentinel-edge
    privileged: true  # Required for eBPF
    pid: host        # Required for process monitoring
    network_mode: host  # Required for network monitoring
    volumes:
      - /sys/fs/bpf:/sys/fs/bpf:rw
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/log/sentinel-edge:/var/log/sentinel-edge:rw
      - ./config:/etc/sentinel-edge:ro
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    
  # 📋 CONCEPTUAL: Supporting services for enterprise deployment
  redis:
    image: redis:7-alpine
    container_name: sentinel-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles: ["enterprise"]  # Only start with --profile enterprise
    
  postgres:
    image: postgres:15-alpine
    container_name: sentinel-postgres
    environment:
      - POSTGRES_USER=sentinel
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-sentinel123}
      - POSTGRES_DB=sentinel_edge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    profiles: ["enterprise"]  # Only start with --profile enterprise
    
  grafana:
    image: grafana/grafana:latest
    container_name: sentinel-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin123}
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    profiles: ["enterprise"]  # Only start with --profile enterprise
    
  prometheus:
    image: prom/prometheus:latest
    container_name: sentinel-prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    profiles: ["enterprise"]  # Only start with --profile enterprise

volumes:
  redis_data:
  postgres_data:
  grafana_data:
  prometheus_data:

networks:
  default:
    name: sentinel-edge-network

# Usage:
# Basic: docker-compose up sentinel-edge
# Enterprise: docker-compose --profile enterprise up 